export default {
    extends: ['@commitlint/config-conventional'],
    rules: {
        'header-max-length': [2, 'always', 100],
        'scope-enum': [
            2,
            'always',
            [
                'docs-app',
                'docs-content',
                'docs-arch',
                'docs-search',
                'docs-ui',
                'docs-i18n',
                'docs-infra',
                'vuln-radar-app',
                'vuln-radar-api',
                'repo-ci',
                'repo-tooling',
                'repo-docs',
                'design-system',
                'workspace',
            ],
        ],
        'subject-case': [0],
        'type-enum': [
            2,
            'always',
            [
                'build',
                'chore',
                'ci',
                'docs',
                'feat',
                'fix',
                'perf',
                'refactor',
                'revert',
                'style',
                'test',
            ],
        ],
    },
}
