import 'server-only'
import { unstable_cache } from 'next/cache'
import { LOCAL_SEARCH_CACHE_TAG } from './content-cache'
import { resolveLocalContentRoot } from './local-content-paths'
import { loadLocalSearchIndex } from './local-search-index'
import { shouldCacheLocalSearchIndex } from './local-search-revision'

// Generated by next.config; it contains no credentials or document text.
const revision = process.env.DOCS_LOCAL_SEARCH_REVISION
const readCachedIndex = unstable_cache(
    loadLocalSearchIndex,
    ['local-search-index-v1', revision ?? ''],
    {
        tags: [LOCAL_SEARCH_CACHE_TAG],
        revalidate: 300,
    }
)

export function getLocalSearchIndex() {
    const root = resolveLocalContentRoot()
    return shouldCacheLocalSearchIndex(process.env.NODE_ENV, revision)
        ? readCachedIndex(root)
        : loadLocalSearchIndex(root)
}
